version: '3'

services:
  kwik_service:
    build:
      context: ./kwik_service
    container_name: kwik_service
    ports:
      - "8000:8000"  # Map host port 8000 to container port 8000 for kwik_service


  ambulance_service:
    build:
      context: ./ambulance_service
    container_name: ambulance_service
    ports:
      - "8001:8001"  # Map host port 8001 to container port 8001 for ambulance_service


  hospital_service:
    build:
      context: ./hospital_service
    container_name: hospital_service
    ports:
      - "8888:8888"  # Map host port 8888 to container port 8888 for hospital_service


  patient_service:
    build:
      context: ./patient_service
    container_name: patient_service
    ports:
      - "8080:8080"  # Map host port 8888 to container port 8888 for hospital_service


networks:
  app-network:
    driver: bridge
