name: Docker Build and Push

on:
  push: # Trigger on push events
    branches:
      - '**' # Matches all branches
  pull_request: # Optional: Trigger on PRs from any branch
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker Compose
    - name: Set up Docker Compose
      run: |
        docker-compose --version || sudo apt-get install -y docker-compose

    # Step 4: Build and tag Docker Compose services
    - name: Build and Tag Docker Compose Services
      run: |
        docker-compose build
